### ISSUE TITLE
Create the first couple of demo tests

### ISSUE THREAD

**Issue by Baasie** [Virtual-Domain-driven-design/virtual-domain-driven-design#33]
does it need any comment, we need something to test with right @yellowbrickc  :D

**Comment by Baasie** [comment]
The easiest and most horrible behaviour to start with will be src/pages/sessions.tsx

Now there needs to be an upcoming session for it to work. If the title is empty then we show no upcoming sessions. So sessions cannot be null.

**Comment by yellowbrickc** [comment]
:tada: first pipeline with first test: 
https://github.com/Virtual-Domain-driven-design/virtual-domain-driven-design/runs/2150474017?check_suite_focus=true

**Comment by yellowbrickc** [comment]
killed linting errors: 12 :grin:
