### ISSUE TITLE
Switch to "gatsby-plugin-image" for better performance and a simpler API.

### ISSUE THREAD

**Issue by Baasie** [Virtual-Domain-driven-design/virtual-domain-driven-design#37]
warn [gatsby-transformer-sharp] The "fixed" and "fluid" resolvers are now deprecated. Switch to "gatsby-plugin-image" for better performance and a simpler API. See
https://gatsby.dev/migrate-images to learn how.

**Comment by yellowbrickc** [comment]
My easter gift for you @Baasie 
Image plugin is migrated :slightly_smiling_face:
