### ISSUE TITLE
Create a nice and usable "no-upcoming-session" page

### ISSUE THREAD

**Issue by yellowbrickc** [Virtual-Domain-driven-design/virtual-domain-driven-design#46]
For a first step, when no upcoming sessions planed a page /session/none will be generated, using the template "no-upcoming-layout.tsx". This page is terribly ugly, sorry for it :( I just removed the whole content and replaced it with the component NoSession and would like to share the work a little bit.

**Comment by flobjective** [comment]
Hi there - I would like to help out. What are looking for in case there is no scheduled session? A link the the last one, plus some nice call to action button and text to let the visitor propose a new session?

**Comment by yellowbrickc** [comment]
Hi @flobjective 
thanks! Your suggestion is really good 👍 
I don't know how much experience you have with gatsby but as a short help for the start: gatsby generates the files on build time, based on the existent templates. The current template for no upcoming templates is here: app/src/templates/no-upcoming-layout.tsx

**Comment by flobjective** [comment]
Thanks for the pointer - I haven't worked with gatsby (yet) - just React. I think I have just passed the biggest hurdle: finding out that you need to add `import "twin.macro"` in every file to get tailwind running 🙃

**Comment by yellowbrickc** [comment]
Thank you a lot @flobjective , it looks very good 👍
